apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability-prod
resources:
  - ../../base
patches:
  - path: grafana-datasource-patch.yml
    target:
      kind: ConfigMap
      name: grafana-datasources
configMapGenerator:
  - name: loki-overrides
    literals:
      - RETENTION_DAYS=30
generatorOptions:
  disableNameSuffixHash: true
