apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ../../base
patchesStrategicMerge:
  - grafana-datasource-patch.yml
configMapGenerator:
  - name: loki-overrides
    literals:
      RETENTION_DAYS=30
generatorOptions:
  disableNameSuffixHash: true
