apiVersion: v1
kind: Service
metadata:
  name: ontu-schedule-bot-admin
spec:
  type: ClusterIP
  selector:
    app: ontu-schedule-bot-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
