---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ontu-schedule-bot-admin
spec:
  template:
    spec:
      containers:
      - name: ontu-schedule-bot-admin
        env:
        - name: ENV
          value: "prod"
        - name: GPU_ENABLED
          value: "1"
        - name: app__security_key
          valueFrom:
            secretKeyRef:
              name: ontu-schedule-bot-admin-secret
              key: app__security_key