---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ontu-schedule-bot-admin
spec:
  template:
    spec:
      containers:
      - name: ontu-schedule-bot-admin
        env:
        - name: app__allowed_hosts
          value: '["ontu-schedule.pavp.pp.ua", "127.0.0.1"]'

        - name: app__security_key
          valueFrom:
            secretKeyRef:
              name: ontu-schedule-bot-admin-secret
              key: app__security_key
        - name: app__db_url
          valueFrom:
            secretKeyRef:
              name: ontu-schedule-bot-admin-secret
              key: app__db_url
        - name: app__redis_url
          valueFrom:
            secretKeyRef:
              name: ontu-schedule-bot-admin-secret
              key: app__redis_url