apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- secret-sealed.yml

patches:
- path: deployment.yml
- path: version.yml
- path: replicas.yml
- path: settings.yml
