# ConfigMap for NGINX configuration
# Contains custom NGINX server configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "example-nginx.fullname" . }}-nginx-config
  labels:
    {{- include "example-nginx.labels" . | nindent 4 }}
data:
  default.conf: |
{{ .Values.nginxConfig | indent 4 }}
