---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ontu-schedule-bot
spec:
  template:
    spec:
      containers:
      - name: ontu-schedule-bot
        env:
        - name: API_URL
          value: "http://ontu-schedule-bot-admin.api-prod.svc.cluster.local:80/api"
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: ontu-schedule-bot-secret
              key: BOT_TOKEN
        - name: API_USERNAME
          valueFrom:
            secretKeyRef:
              name: ontu-schedule-bot-secret
              key: API_USERNAME
        - name: API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ontu-schedule-bot-secret
              key: API_PASSWORD
        - name: DEBUG_CHAT_ID
          valueFrom:
            secretKeyRef:
              name: ontu-schedule-bot-secret
              key: DEBUG_CHAT_ID
        - name: WEBHOOK_URL
          value: "https://ontu-schedule-bot.pavp.pp.ua"
