{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ontu-schedule-bot-admin.fullname" . }}
  labels:
    {{- include "ontu-schedule-bot-admin.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
{{- end }}
